[project]
name = "camero"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "EP", email = "ep@example.com" }
]
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.24",
    "strawberry-graphql[fastapi]>=0.240",
    "sqlalchemy>=2.0",
    "pillow>=10.0",
    "numpy>=2.0",
    "pandas>=2.2",
    "hachoir>=3.3.0",
    "opencv-python>=4.10",
    "onnxruntime-directml>=1.24.4; platform_system == 'Windows'",
    "onnxruntime>=1.24.0; platform_system != 'Windows'",
]

[project.scripts]
camero = "camero.main:main"

[dependency-groups]
dev = [
  
]

